//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace task_3rd_feb.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Employee
    {
  
        
        [Required]
        public int Id { get; set; }

        [Required]
        [StringLength(12)]
        [Display(Name = "First Name")]
        public string First_Name { get; set; }

        [Required]
        [StringLength(12)]
        [Display(Name = "Last Name")]
        public string Last_Name { get; set; }



        [Required]
        [EmailAddress]
        public string Email { get; set; }

        [Required]
        [RegularExpression("((079)|(078)|(077)){1}[0-9]{7}", ErrorMessage = "Enter A Valid Jordanian Phone Number")]
        public string Phone { get; set; }
        [Required]
        [Range(18, 50)]
        public Nullable<int> Age { get; set; }
        [Required]
        [StringLength(10)]
        [Display(Name = "Job Title")]

        public string Job_Title { get; set; }
        [Required]

        public Nullable<bool> Gender { get; set; }

        [Required]
        public string Images { get; set; }

        [Required]
        public string CV { get; set; }
    }
}
